package dev.slne.surf.shulker.api

object ShulkerKeys {
    private const val PREFIX = "shulker"

    const val ID = "${PREFIX}:id"
    const val NAME = "${PREFIX}:name"
    const val STATE = "${PREFIX}:state"
    const val TYPE = "${PREFIX}:type"
    const val GROUP_NAME = "${PREFIX}:group_name"
    const val HOSTNAME = "${PREFIX}:hostname"
    const val PORT = "${PREFIX}:port"
    const val CREATED_AT = "${PREFIX}:created_at"
    const val START_THRESHOLD = "${PREFIX}:start_threshold"
    const val PLATFORM = "${PREFIX}:platform"
    const val MIN_MEMORY = "${PREFIX}:min_memory"
    const val MAX_MEMORY = "${PREFIX}:max_memory"
    const val MIN_ONLINE = "${PREFIX}:min_online"
    const val MAX_ONLINE = "${PREFIX}:max_online"
    const val PLAYER_COUNT = "${PREFIX}:player_count"
    const val MAX_PLAYER_COUNT = "${PREFIX}:max_player_count"
    const val MEMORY_USAGE = "${PREFIX}:memory_usage"
    const val CPU_USAGE = "${PREFIX}:cpu_usage"
    const val MOTD = "${PREFIX}:motd"
    const val TEMPLATES = "${PREFIX}:templates"
    const val PROPERTIES = "${PREFIX}:properties"
    const val VERSION = "${PREFIX}:version"
    const val VERSIONS = "${PREFIX}:versions"
    const val INFORMATION = "${PREFIX}:information"
    const val UNIQUE_ID = "${PREFIX}:unique_id"
    const val SIZE = "${PREFIX}:size"
    const val CURRENT_SERVER_NAME = "${PREFIX}:current_server_name"
    const val CURRENT_PROXY_NAME = "${PREFIX}:current_proxy_name"
}